package texteditor.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Copy" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("texteditor.dal.PDCopy");
 * @author PDGen
 */
public class PDCopy implements PDInstance {

	public static final GUID typeId = new GUID("3c08266654d111e09c2a001e6805726d"); 

	public static final GUID roleOriginalWordId = new GUID("3c08267154d111e09c2a001e6805726d");
	public static final GUID roleTypeId = new GUID("ee32adf0f68b11df860e1cc1dec00ed3");
	public static final GUID roleNewWordId = new GUID("3c08267254d111e09c2a001e6805726d");
	public static final GUID roleToAfterId = new GUID("3c08267354d111e09c2a001e6805726d");

	static {
		DALClassRegister.addDataClass(typeId, PDCopy.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDCopy:" + name;
		else
			return "PDCopy:" + id;
	}
	/**
	 * Creates an PDCopy object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDCopy(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDCopy object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDCopy(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
		// set has-type link as specified in the model, if it does not exist yet
		if (workingCopy.getInstance(this, PDStore.HAS_TYPE_ROLEID) == null)
			workingCopy.addLink(id, PDStore.HAS_TYPE_ROLEID, typeId);
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDCopy load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDCopy)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "originalWord".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDWord getOriginalWord() throws PDStoreException {
	 	return (PDWord)pdWorkingCopy.getInstance(this, roleOriginalWordId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "originalWord".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDWord> getOriginalWords() throws PDStoreException {
	 	Set<PDWord> result = new HashSet<PDWord>();
	 	GUID PDWordTypeId = new GUID("3c08266254d111e09c2a001e6805726d");
		pdWorkingCopy.getInstances(this, roleOriginalWordId, PDWord.class, PDWordTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "originalWord".
	 * If the given instance is null, nothing happens.
	 * @param originalWord the instance to connect
	 * @throws PDStoreException
	 */
	public void addOriginalWord(GUID originalWord) throws PDStoreException {

			if (originalWord != null) {
				
				pdWorkingCopy.addLink(this.id, roleOriginalWordId, originalWord);
			}

	}

	/**
	 * Connects this instance to the given instance using role "originalWord".
	 * If the given instance is null, nothing happens.
	 * @param originalWord the instance to connect
	 * @throws PDStoreException
	 */
	public void addOriginalWord(PDWord originalWord) throws PDStoreException {
		if (originalWord != null) {
			addOriginalWord(originalWord.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "originalWord".
	 * @throws PDStoreException
	 */
	public void removeOriginalWord() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleOriginalWordId, 
			pdWorkingCopy.getInstance(this, roleOriginalWordId));
	}

	/**
	 * Removes the link from this instance through role "originalWord" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.originalWord.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeOriginalWord(Object originalWord) throws PDStoreException {
		if (originalWord==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleOriginalWordId, originalWord);
	}

   /**
	 * Connects this instance to the given instance using role "originalWord".
	 * If there is already an instance connected to this instance through role "originalWord", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param originalWord the instance to connect
	 * @throws PDStoreException
	 */
	public void setOriginalWord(GUID originalWord) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleOriginalWordId, originalWord);	
	}
	/**
	 * Connects this instance to the given instance using role "originalWord".
	 * If there is already an instance connected to this instance through role "originalWord", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param originalWord the instance to connect
	 * @throws PDStoreException
	 */
	public void setOriginalWord(PDWord originalWord) throws PDStoreException {
		setOriginalWord(originalWord.getId());
	}

  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "type".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDType getType() throws PDStoreException {
	 	return (PDType)pdWorkingCopy.getInstance(this, roleTypeId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "type".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDType> getTypes() throws PDStoreException {
	 	Set<PDType> result = new HashSet<PDType>();
	 	GUID PDTypeTypeId = new GUID("518a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleTypeId, PDType.class, PDTypeTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "type".
	 * If the given instance is null, nothing happens.
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void addType(GUID type) throws PDStoreException {

			if (type != null) {
				
				pdWorkingCopy.addLink(this.id, roleTypeId, type);
			}

	}

	/**
	 * Connects this instance to the given instance using role "type".
	 * If the given instance is null, nothing happens.
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void addType(PDType type) throws PDStoreException {
		if (type != null) {
			addType(type.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "type".
	 * @throws PDStoreException
	 */
	public void removeType() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleTypeId, 
			pdWorkingCopy.getInstance(this, roleTypeId));
	}

	/**
	 * Removes the link from this instance through role "type" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.type.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeType(Object type) throws PDStoreException {
		if (type==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleTypeId, type);
	}

   /**
	 * Connects this instance to the given instance using role "type".
	 * If there is already an instance connected to this instance through role "type", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void setType(GUID type) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleTypeId, type);	
	}
	/**
	 * Connects this instance to the given instance using role "type".
	 * If there is already an instance connected to this instance through role "type", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void setType(PDType type) throws PDStoreException {
		setType(type.getId());
	}

  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "newWord".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDWord getNewWord() throws PDStoreException {
	 	return (PDWord)pdWorkingCopy.getInstance(this, roleNewWordId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "newWord".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDWord> getNewWords() throws PDStoreException {
	 	Set<PDWord> result = new HashSet<PDWord>();
	 	GUID PDWordTypeId = new GUID("3c08266254d111e09c2a001e6805726d");
		pdWorkingCopy.getInstances(this, roleNewWordId, PDWord.class, PDWordTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "newWord".
	 * If the given instance is null, nothing happens.
	 * @param newWord the instance to connect
	 * @throws PDStoreException
	 */
	public void addNewWord(GUID newWord) throws PDStoreException {

			if (newWord != null) {
				
				pdWorkingCopy.addLink(this.id, roleNewWordId, newWord);
			}

	}

	/**
	 * Connects this instance to the given instance using role "newWord".
	 * If the given instance is null, nothing happens.
	 * @param newWord the instance to connect
	 * @throws PDStoreException
	 */
	public void addNewWord(PDWord newWord) throws PDStoreException {
		if (newWord != null) {
			addNewWord(newWord.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "newWord".
	 * @throws PDStoreException
	 */
	public void removeNewWord() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleNewWordId, 
			pdWorkingCopy.getInstance(this, roleNewWordId));
	}

	/**
	 * Removes the link from this instance through role "newWord" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.newWord.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeNewWord(Object newWord) throws PDStoreException {
		if (newWord==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleNewWordId, newWord);
	}

   /**
	 * Connects this instance to the given instance using role "newWord".
	 * If there is already an instance connected to this instance through role "newWord", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param newWord the instance to connect
	 * @throws PDStoreException
	 */
	public void setNewWord(GUID newWord) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleNewWordId, newWord);	
	}
	/**
	 * Connects this instance to the given instance using role "newWord".
	 * If there is already an instance connected to this instance through role "newWord", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param newWord the instance to connect
	 * @throws PDStoreException
	 */
	public void setNewWord(PDWord newWord) throws PDStoreException {
		setNewWord(newWord.getId());
	}

  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "toAfter".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDWord getToAfter() throws PDStoreException {
	 	return (PDWord)pdWorkingCopy.getInstance(this, roleToAfterId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "toAfter".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDWord> getToAfters() throws PDStoreException {
	 	Set<PDWord> result = new HashSet<PDWord>();
	 	GUID PDWordTypeId = new GUID("3c08266254d111e09c2a001e6805726d");
		pdWorkingCopy.getInstances(this, roleToAfterId, PDWord.class, PDWordTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "toAfter".
	 * If the given instance is null, nothing happens.
	 * @param toAfter the instance to connect
	 * @throws PDStoreException
	 */
	public void addToAfter(GUID toAfter) throws PDStoreException {

			if (toAfter != null) {
				
				pdWorkingCopy.addLink(this.id, roleToAfterId, toAfter);
			}

	}

	/**
	 * Connects this instance to the given instance using role "toAfter".
	 * If the given instance is null, nothing happens.
	 * @param toAfter the instance to connect
	 * @throws PDStoreException
	 */
	public void addToAfter(PDWord toAfter) throws PDStoreException {
		if (toAfter != null) {
			addToAfter(toAfter.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "toAfter".
	 * @throws PDStoreException
	 */
	public void removeToAfter() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleToAfterId, 
			pdWorkingCopy.getInstance(this, roleToAfterId));
	}

	/**
	 * Removes the link from this instance through role "toAfter" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.toAfter.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeToAfter(Object toAfter) throws PDStoreException {
		if (toAfter==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleToAfterId, toAfter);
	}

   /**
	 * Connects this instance to the given instance using role "toAfter".
	 * If there is already an instance connected to this instance through role "toAfter", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param toAfter the instance to connect
	 * @throws PDStoreException
	 */
	public void setToAfter(GUID toAfter) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleToAfterId, toAfter);	
	}
	/**
	 * Connects this instance to the given instance using role "toAfter".
	 * If there is already an instance connected to this instance through role "toAfter", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param toAfter the instance to connect
	 * @throws PDStoreException
	 */
	public void setToAfter(PDWord toAfter) throws PDStoreException {
		setToAfter(toAfter.getId());
	}

}
