package angil.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Page" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("angil.dal.PDPage");
 * @author PDGen
 */
public class PDPage implements PDInstance {

	public static final GUID typeId = new GUID("fbc29377374c11e0bfe4001e8c7f9d82"); 

	public static final GUID roleNextActionId = new GUID("005319b036ed11e08144001e8c7f9d82");

	static {
		DALClassRegister.addDataClass(typeId, PDPage.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDPage:" + name;
		else
			return "PDPage:" + id;
	}
	/**
	 * Creates an PDPage object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDPage(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDPage object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDPage(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDPage load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDPage)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "nextAction".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDAction getNextAction() throws PDStoreException {
	 	return (PDAction)pdWorkingCopy.getInstance(this, roleNextActionId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "nextAction".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDAction> getNextActions() throws PDStoreException {
	 	Set<PDAction> result = new HashSet<PDAction>();
	 	GUID PDActionTypeId = new GUID("fbc29378374c11e0bfe4001e8c7f9d82");
		pdWorkingCopy.getInstances(this, roleNextActionId, PDAction.class, PDActionTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "nextAction".
	 * If the given instance is null, nothing happens.
	 * @param nextAction the instance to connect
	 * @throws PDStoreException
	 */
	public void addNextAction(GUID nextAction) throws PDStoreException {

			if (nextAction != null) {
				
				pdWorkingCopy.addLink(this.id, roleNextActionId, nextAction);
			}

	}

	/**
	 * Connects this instance to the given instance using role "nextAction".
	 * If the given instance is null, nothing happens.
	 * @param nextAction the instance to connect
	 * @throws PDStoreException
	 */
	public void addNextAction(PDAction nextAction) throws PDStoreException {
		if (nextAction != null) {
			addNextAction(nextAction.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "nextAction".
	 * @throws PDStoreException
	 */
	public void removeNextAction() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleNextActionId, 
			pdWorkingCopy.getInstance(this, roleNextActionId));
	}

	/**
	 * Removes the link from this instance through role "nextAction" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.nextAction.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeNextAction(Object nextAction) throws PDStoreException {
		if (nextAction==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleNextActionId, nextAction);
	}

   /**
	 * Connects this instance to the given instance using role "nextAction".
	 * If there is already an instance connected to this instance through role "nextAction", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param nextAction the instance to connect
	 * @throws PDStoreException
	 */
	public void setNextAction(GUID nextAction) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleNextActionId, nextAction);	
	}
	/**
	 * Connects this instance to the given instance using role "nextAction".
	 * If there is already an instance connected to this instance through role "nextAction", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param nextAction the instance to connect
	 * @throws PDStoreException
	 */
	public void setNextAction(PDAction nextAction) throws PDStoreException {
		setNextAction(nextAction.getId());
	}

}
