package pdtransform.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Address Book" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("pdtransform.dal.PDAddressBook");
 * @author PDGen
 */
public class PDAddressBook implements PDInstance {

	public static final GUID typeId = new GUID("e85c1f278e0ede11980f9a097666e103"); 

	public static final GUID roleSubAddressBookId = new GUID("115d1f278e0ede11980f9a097666e103");
	public static final GUID roleContactId = new GUID("eb5c1f278e0ede11980f9a097666e103");
	public static final GUID roleLabelId = new GUID("afba85348e0ede11980f9a097666e103");

	static {
		DALClassRegister.addDataClass(typeId, PDAddressBook.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDAddressBook:" + name;
		else
			return "PDAddressBook:" + id;
	}
	/**
	 * Creates an PDAddressBook object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDAddressBook(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDAddressBook object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDAddressBook(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDAddressBook load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDAddressBook)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "sub address book".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDAddressBook getSubAddressBook() throws PDStoreException {
	 	return (PDAddressBook)pdWorkingCopy.getInstance(this, roleSubAddressBookId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "sub address book".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDAddressBook> getSubAddressBooks() throws PDStoreException {
	 	Set<PDAddressBook> result = new HashSet<PDAddressBook>();
	 	GUID PDAddressBookTypeId = new GUID("e85c1f278e0ede11980f9a097666e103");
		pdWorkingCopy.getInstances(this, roleSubAddressBookId, PDAddressBook.class, PDAddressBookTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "sub address book".
	 * If the given instance is null, nothing happens.
	 * @param subAddressBook the instance to connect
	 * @throws PDStoreException
	 */
	public void addSubAddressBook(GUID subAddressBook) throws PDStoreException {

			if (subAddressBook != null) {
				
				pdWorkingCopy.addLink(this.id, roleSubAddressBookId, subAddressBook);
			}

	}

	/**
	 * Connects this instance to the given instance using role "sub address book".
	 * If the given instance is null, nothing happens.
	 * @param subAddressBook the instance to connect
	 * @throws PDStoreException
	 */
	public void addSubAddressBook(PDAddressBook subAddressBook) throws PDStoreException {
		if (subAddressBook != null) {
			addSubAddressBook(subAddressBook.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "sub address book".
	 * @throws PDStoreException
	 */
	public void removeSubAddressBook() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleSubAddressBookId, 
			pdWorkingCopy.getInstance(this, roleSubAddressBookId));
	}

	/**
	 * Removes the link from this instance through role "sub address book" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.subAddressBook.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeSubAddressBook(Object subAddressBook) throws PDStoreException {
		if (subAddressBook==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleSubAddressBookId, subAddressBook);
	}

   /**
	 * Connects this instance to the given instance using role "sub address book".
	 * If there is already an instance connected to this instance through role "sub address book", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param subAddressBook the instance to connect
	 * @throws PDStoreException
	 */
	public void setSubAddressBook(GUID subAddressBook) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleSubAddressBookId, subAddressBook);	
	}
	/**
	 * Connects this instance to the given instance using role "sub address book".
	 * If there is already an instance connected to this instance through role "sub address book", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param subAddressBook the instance to connect
	 * @throws PDStoreException
	 */
	public void setSubAddressBook(PDAddressBook subAddressBook) throws PDStoreException {
		setSubAddressBook(subAddressBook.getId());
	}

  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "contact".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDContact getContact() throws PDStoreException {
	 	return (PDContact)pdWorkingCopy.getInstance(this, roleContactId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "contact".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDContact> getContacts() throws PDStoreException {
	 	Set<PDContact> result = new HashSet<PDContact>();
	 	GUID PDContactTypeId = new GUID("e95c1f278e0ede11980f9a097666e103");
		pdWorkingCopy.getInstances(this, roleContactId, PDContact.class, PDContactTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "contact".
	 * If the given instance is null, nothing happens.
	 * @param contact the instance to connect
	 * @throws PDStoreException
	 */
	public void addContact(GUID contact) throws PDStoreException {

			if (contact != null) {
				
				pdWorkingCopy.addLink(this.id, roleContactId, contact);
			}

	}

	/**
	 * Connects this instance to the given instance using role "contact".
	 * If the given instance is null, nothing happens.
	 * @param contact the instance to connect
	 * @throws PDStoreException
	 */
	public void addContact(PDContact contact) throws PDStoreException {
		if (contact != null) {
			addContact(contact.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "contact".
	 * @throws PDStoreException
	 */
	public void removeContact() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleContactId, 
			pdWorkingCopy.getInstance(this, roleContactId));
	}

	/**
	 * Removes the link from this instance through role "contact" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.contact.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeContact(Object contact) throws PDStoreException {
		if (contact==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleContactId, contact);
	}

   /**
	 * Connects this instance to the given instance using role "contact".
	 * If there is already an instance connected to this instance through role "contact", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param contact the instance to connect
	 * @throws PDStoreException
	 */
	public void setContact(GUID contact) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleContactId, contact);	
	}
	/**
	 * Connects this instance to the given instance using role "contact".
	 * If there is already an instance connected to this instance through role "contact", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param contact the instance to connect
	 * @throws PDStoreException
	 */
	public void setContact(PDContact contact) throws PDStoreException {
		setContact(contact.getId());
	}

  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "label".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public String getLabel() throws PDStoreException {
	 	return (String)pdWorkingCopy.getInstance(this, roleLabelId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "label".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<String> getLabels() throws PDStoreException {
	 	Set<String> result = new HashSet<String>();
	 	GUID StringTypeId = new GUID("4a8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleLabelId, String.class, StringTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "label".
	 * If the given instance is null, nothing happens.
	 * @param label the instance to connect
	 * @throws PDStoreException
	 */
	public void addLabel(String label) throws PDStoreException {

			if (label != null) {
				
				pdWorkingCopy.addLink(this.id, roleLabelId, label);
			}

	}


	/**
	 * Removes the link from this instance through role "label".
	 * @throws PDStoreException
	 */
	public void removeLabel() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleLabelId, 
			pdWorkingCopy.getInstance(this, roleLabelId));
	}

	/**
	 * Removes the link from this instance through role "label" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.label.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeLabel(Object label) throws PDStoreException {
		if (label==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleLabelId, label);
	}

   /**
	 * Connects this instance to the given instance using role "label".
	 * If there is already an instance connected to this instance through role "label", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param label the instance to connect
	 * @throws PDStoreException
	 */
	public void setLabel(String label) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleLabelId, label);	
	}
}
