package pdtransform.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Contact" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("pdtransform.dal.PDContact");
 * @author PDGen
 */
public class PDContact implements PDInstance {

	public static final GUID typeId = new GUID("e95c1f278e0ede11980f9a097666e103"); 

	public static final GUID roleContactsNameId = new GUID("0d5d1f278e0ede11980f9a097666e103");
	public static final GUID roleAddressId = new GUID("0f5d1f278e0ede11980f9a097666e103");

	static {
		DALClassRegister.addDataClass(typeId, PDContact.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDContact:" + name;
		else
			return "PDContact:" + id;
	}
	/**
	 * Creates an PDContact object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDContact(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDContact object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDContact(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDContact load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDContact)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "contacts name".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public String getContactsName() throws PDStoreException {
	 	return (String)pdWorkingCopy.getInstance(this, roleContactsNameId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "contacts name".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<String> getContactsNames() throws PDStoreException {
	 	Set<String> result = new HashSet<String>();
	 	GUID StringTypeId = new GUID("4a8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleContactsNameId, String.class, StringTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "contacts name".
	 * If the given instance is null, nothing happens.
	 * @param contactsName the instance to connect
	 * @throws PDStoreException
	 */
	public void addContactsName(String contactsName) throws PDStoreException {

			if (contactsName != null) {
				
				pdWorkingCopy.addLink(this.id, roleContactsNameId, contactsName);
			}

	}


	/**
	 * Removes the link from this instance through role "contacts name".
	 * @throws PDStoreException
	 */
	public void removeContactsName() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleContactsNameId, 
			pdWorkingCopy.getInstance(this, roleContactsNameId));
	}

	/**
	 * Removes the link from this instance through role "contacts name" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.contactsName.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeContactsName(Object contactsName) throws PDStoreException {
		if (contactsName==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleContactsNameId, contactsName);
	}

   /**
	 * Connects this instance to the given instance using role "contacts name".
	 * If there is already an instance connected to this instance through role "contacts name", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param contactsName the instance to connect
	 * @throws PDStoreException
	 */
	public void setContactsName(String contactsName) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleContactsNameId, contactsName);	
	}
  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "address".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public String getAddress() throws PDStoreException {
	 	return (String)pdWorkingCopy.getInstance(this, roleAddressId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "address".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<String> getAddresss() throws PDStoreException {
	 	Set<String> result = new HashSet<String>();
	 	GUID StringTypeId = new GUID("4a8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleAddressId, String.class, StringTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "address".
	 * If the given instance is null, nothing happens.
	 * @param address the instance to connect
	 * @throws PDStoreException
	 */
	public void addAddress(String address) throws PDStoreException {

			if (address != null) {
				
				pdWorkingCopy.addLink(this.id, roleAddressId, address);
			}

	}


	/**
	 * Removes the link from this instance through role "address".
	 * @throws PDStoreException
	 */
	public void removeAddress() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleAddressId, 
			pdWorkingCopy.getInstance(this, roleAddressId));
	}

	/**
	 * Removes the link from this instance through role "address" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.address.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeAddress(Object address) throws PDStoreException {
		if (address==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleAddressId, address);
	}

   /**
	 * Connects this instance to the given instance using role "address".
	 * If there is already an instance connected to this instance through role "address", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param address the instance to connect
	 * @throws PDStoreException
	 */
	public void setAddress(String address) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleAddressId, address);	
	}
}
