package pdtransform.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "HTML tag" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("pdtransform.dal.PDHTMLTag");
 * @author PDGen
 */
public class PDHTMLTag implements PDInstance {

	public static final GUID typeId = new GUID("f25c1f278e0ede11980f9a097666e103"); 

	public static final GUID roleTextId = new GUID("adba85348e0ede11980f9a097666e103");
	public static final GUID roleChildId = new GUID("f65c1f278e0ede11980f9a097666e103");

	static {
		DALClassRegister.addDataClass(typeId, PDHTMLTag.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDHTMLTag:" + name;
		else
			return "PDHTMLTag:" + id;
	}
	/**
	 * Creates an PDHTMLTag object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDHTMLTag(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDHTMLTag object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDHTMLTag(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDHTMLTag load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDHTMLTag)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "text".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDText getText() throws PDStoreException {
	 	return (PDText)pdWorkingCopy.getInstance(this, roleTextId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "text".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDText> getTexts() throws PDStoreException {
	 	Set<PDText> result = new HashSet<PDText>();
	 	GUID PDTextTypeId = new GUID("caba85348e0ede11980f9a097666e103");
		pdWorkingCopy.getInstances(this, roleTextId, PDText.class, PDTextTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "text".
	 * If the given instance is null, nothing happens.
	 * @param text the instance to connect
	 * @throws PDStoreException
	 */
	public void addText(GUID text) throws PDStoreException {

			if (text != null) {
				
				pdWorkingCopy.addLink(this.id, roleTextId, text);
			}

	}

	/**
	 * Connects this instance to the given instance using role "text".
	 * If the given instance is null, nothing happens.
	 * @param text the instance to connect
	 * @throws PDStoreException
	 */
	public void addText(PDText text) throws PDStoreException {
		if (text != null) {
			addText(text.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "text".
	 * @throws PDStoreException
	 */
	public void removeText() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleTextId, 
			pdWorkingCopy.getInstance(this, roleTextId));
	}

	/**
	 * Removes the link from this instance through role "text" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.text.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeText(Object text) throws PDStoreException {
		if (text==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleTextId, text);
	}

   /**
	 * Connects this instance to the given instance using role "text".
	 * If there is already an instance connected to this instance through role "text", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param text the instance to connect
	 * @throws PDStoreException
	 */
	public void setText(GUID text) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleTextId, text);	
	}
	/**
	 * Connects this instance to the given instance using role "text".
	 * If there is already an instance connected to this instance through role "text", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param text the instance to connect
	 * @throws PDStoreException
	 */
	public void setText(PDText text) throws PDStoreException {
		setText(text.getId());
	}

  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "child".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDULTag getChild() throws PDStoreException {
	 	return (PDULTag)pdWorkingCopy.getInstance(this, roleChildId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "child".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDULTag> getChilds() throws PDStoreException {
	 	Set<PDULTag> result = new HashSet<PDULTag>();
	 	GUID PDULTagTypeId = new GUID("f35c1f278e0ede11980f9a097666e103");
		pdWorkingCopy.getInstances(this, roleChildId, PDULTag.class, PDULTagTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "child".
	 * If the given instance is null, nothing happens.
	 * @param child the instance to connect
	 * @throws PDStoreException
	 */
	public void addChild(GUID child) throws PDStoreException {

			if (child != null) {
				
				pdWorkingCopy.addLink(this.id, roleChildId, child);
			}

	}

	/**
	 * Connects this instance to the given instance using role "child".
	 * If the given instance is null, nothing happens.
	 * @param child the instance to connect
	 * @throws PDStoreException
	 */
	public void addChild(PDULTag child) throws PDStoreException {
		if (child != null) {
			addChild(child.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "child".
	 * @throws PDStoreException
	 */
	public void removeChild() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleChildId, 
			pdWorkingCopy.getInstance(this, roleChildId));
	}

	/**
	 * Removes the link from this instance through role "child" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.child.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeChild(Object child) throws PDStoreException {
		if (child==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleChildId, child);
	}

   /**
	 * Connects this instance to the given instance using role "child".
	 * If there is already an instance connected to this instance through role "child", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param child the instance to connect
	 * @throws PDStoreException
	 */
	public void setChild(GUID child) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleChildId, child);	
	}
	/**
	 * Connects this instance to the given instance using role "child".
	 * If there is already an instance connected to this instance through role "child", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param child the instance to connect
	 * @throws PDStoreException
	 */
	public void setChild(PDULTag child) throws PDStoreException {
		setChild(child.getId());
	}

}
