package pdtransform.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Ordered Pair" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("pdtransform.dal.PDOrderedPair");
 * @author PDGen
 */
public class PDOrderedPair implements PDInstance {

	public static final GUID typeId = new GUID("b3ba85348e0ede11980f9a097666e103"); 

	public static final GUID rolePrevId = new GUID("b9ba85348e0ede11980f9a097666e103");
	public static final GUID roleNextId = new GUID("bbba85348e0ede11980f9a097666e103");

	static {
		DALClassRegister.addDataClass(typeId, PDOrderedPair.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDOrderedPair:" + name;
		else
			return "PDOrderedPair:" + id;
	}
	/**
	 * Creates an PDOrderedPair object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDOrderedPair(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDOrderedPair object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDOrderedPair(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDOrderedPair load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDOrderedPair)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "prev".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public GUID getPrev() throws PDStoreException {
	 	return (GUID)pdWorkingCopy.getInstance(this, rolePrevId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "prev".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<GUID> getPrevs() throws PDStoreException {
	 	Set<GUID> result = new HashSet<GUID>();
	 	GUID GUIDTypeId = new GUID("538a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, rolePrevId, GUID.class, GUIDTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "prev".
	 * If the given instance is null, nothing happens.
	 * @param prev the instance to connect
	 * @throws PDStoreException
	 */
	public void addPrev(GUID prev) throws PDStoreException {

			if (prev != null) {
				
				pdWorkingCopy.addLink(this.id, rolePrevId, prev);
			}

	}


	/**
	 * Removes the link from this instance through role "prev".
	 * @throws PDStoreException
	 */
	public void removePrev() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, rolePrevId, 
			pdWorkingCopy.getInstance(this, rolePrevId));
	}

	/**
	 * Removes the link from this instance through role "prev" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.prev.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removePrev(Object prev) throws PDStoreException {
		if (prev==null)
			return;
		pdWorkingCopy.removeLink(this.id, rolePrevId, prev);
	}

   /**
	 * Connects this instance to the given instance using role "prev".
	 * If there is already an instance connected to this instance through role "prev", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param prev the instance to connect
	 * @throws PDStoreException
	 */
	public void setPrev(GUID prev) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  rolePrevId, prev);	
	}
  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "next".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public GUID getNext() throws PDStoreException {
	 	return (GUID)pdWorkingCopy.getInstance(this, roleNextId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "next".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<GUID> getNexts() throws PDStoreException {
	 	Set<GUID> result = new HashSet<GUID>();
	 	GUID GUIDTypeId = new GUID("538a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleNextId, GUID.class, GUIDTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "next".
	 * If the given instance is null, nothing happens.
	 * @param next the instance to connect
	 * @throws PDStoreException
	 */
	public void addNext(GUID next) throws PDStoreException {

			if (next != null) {
				
				pdWorkingCopy.addLink(this.id, roleNextId, next);
			}

	}


	/**
	 * Removes the link from this instance through role "next".
	 * @throws PDStoreException
	 */
	public void removeNext() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleNextId, 
			pdWorkingCopy.getInstance(this, roleNextId));
	}

	/**
	 * Removes the link from this instance through role "next" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.next.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeNext(Object next) throws PDStoreException {
		if (next==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleNextId, next);
	}

   /**
	 * Connects this instance to the given instance using role "next".
	 * If there is already an instance connected to this instance through role "next", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param next the instance to connect
	 * @throws PDStoreException
	 */
	public void setNext(GUID next) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleNextId, next);	
	}
}
