package pdtransform.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Print Instruction" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("pdtransform.dal.PDPrintInstruction");
 * @author PDGen
 */
public class PDPrintInstruction implements PDInstance {

	public static final GUID typeId = new GUID("621e85348e0ede11980f9a097666e103"); 

	public static final GUID rolePrintBeforeId = new GUID("661e85348e0ede11980f9a097666e103");
	public static final GUID rolePrintAfterId = new GUID("681e85348e0ede11980f9a097666e103");
	public static final GUID roleTypeId = new GUID("641e85348e0ede11980f9a097666e103");

	static {
		DALClassRegister.addDataClass(typeId, PDPrintInstruction.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDPrintInstruction:" + name;
		else
			return "PDPrintInstruction:" + id;
	}
	/**
	 * Creates an PDPrintInstruction object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDPrintInstruction(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDPrintInstruction object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDPrintInstruction(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDPrintInstruction load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDPrintInstruction)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "print before".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public String getPrintBefore() throws PDStoreException {
	 	return (String)pdWorkingCopy.getInstance(this, rolePrintBeforeId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "print before".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<String> getPrintBefores() throws PDStoreException {
	 	Set<String> result = new HashSet<String>();
	 	GUID StringTypeId = new GUID("4a8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, rolePrintBeforeId, String.class, StringTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "print before".
	 * If the given instance is null, nothing happens.
	 * @param printBefore the instance to connect
	 * @throws PDStoreException
	 */
	public void addPrintBefore(String printBefore) throws PDStoreException {

			if (printBefore != null) {
				
				pdWorkingCopy.addLink(this.id, rolePrintBeforeId, printBefore);
			}

	}


	/**
	 * Removes the link from this instance through role "print before".
	 * @throws PDStoreException
	 */
	public void removePrintBefore() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, rolePrintBeforeId, 
			pdWorkingCopy.getInstance(this, rolePrintBeforeId));
	}

	/**
	 * Removes the link from this instance through role "print before" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.printBefore.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removePrintBefore(Object printBefore) throws PDStoreException {
		if (printBefore==null)
			return;
		pdWorkingCopy.removeLink(this.id, rolePrintBeforeId, printBefore);
	}

   /**
	 * Connects this instance to the given instance using role "print before".
	 * If there is already an instance connected to this instance through role "print before", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param printBefore the instance to connect
	 * @throws PDStoreException
	 */
	public void setPrintBefore(String printBefore) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  rolePrintBeforeId, printBefore);	
	}
  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "print after".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public String getPrintAfter() throws PDStoreException {
	 	return (String)pdWorkingCopy.getInstance(this, rolePrintAfterId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "print after".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<String> getPrintAfters() throws PDStoreException {
	 	Set<String> result = new HashSet<String>();
	 	GUID StringTypeId = new GUID("4a8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, rolePrintAfterId, String.class, StringTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "print after".
	 * If the given instance is null, nothing happens.
	 * @param printAfter the instance to connect
	 * @throws PDStoreException
	 */
	public void addPrintAfter(String printAfter) throws PDStoreException {

			if (printAfter != null) {
				
				pdWorkingCopy.addLink(this.id, rolePrintAfterId, printAfter);
			}

	}


	/**
	 * Removes the link from this instance through role "print after".
	 * @throws PDStoreException
	 */
	public void removePrintAfter() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, rolePrintAfterId, 
			pdWorkingCopy.getInstance(this, rolePrintAfterId));
	}

	/**
	 * Removes the link from this instance through role "print after" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.printAfter.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removePrintAfter(Object printAfter) throws PDStoreException {
		if (printAfter==null)
			return;
		pdWorkingCopy.removeLink(this.id, rolePrintAfterId, printAfter);
	}

   /**
	 * Connects this instance to the given instance using role "print after".
	 * If there is already an instance connected to this instance through role "print after", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param printAfter the instance to connect
	 * @throws PDStoreException
	 */
	public void setPrintAfter(String printAfter) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  rolePrintAfterId, printAfter);	
	}
  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "type".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDType getType() throws PDStoreException {
	 	return (PDType)pdWorkingCopy.getInstance(this, roleTypeId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "type".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDType> getTypes() throws PDStoreException {
	 	Set<PDType> result = new HashSet<PDType>();
	 	GUID PDTypeTypeId = new GUID("518a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleTypeId, PDType.class, PDTypeTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "type".
	 * If the given instance is null, nothing happens.
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void addType(GUID type) throws PDStoreException {

			if (type != null) {
				
				pdWorkingCopy.addLink(this.id, roleTypeId, type);
			}

	}

	/**
	 * Connects this instance to the given instance using role "type".
	 * If the given instance is null, nothing happens.
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void addType(PDType type) throws PDStoreException {
		if (type != null) {
			addType(type.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "type".
	 * @throws PDStoreException
	 */
	public void removeType() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleTypeId, 
			pdWorkingCopy.getInstance(this, roleTypeId));
	}

	/**
	 * Removes the link from this instance through role "type" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.type.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeType(Object type) throws PDStoreException {
		if (type==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleTypeId, type);
	}

   /**
	 * Connects this instance to the given instance using role "type".
	 * If there is already an instance connected to this instance through role "type", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void setType(GUID type) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleTypeId, type);	
	}
	/**
	 * Connects this instance to the given instance using role "type".
	 * If there is already an instance connected to this instance through role "type", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param type the instance to connect
	 * @throws PDStoreException
	 */
	public void setType(PDType type) throws PDStoreException {
		setType(type.getId());
	}

}
