package pdtransform.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Serializer" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("pdtransform.dal.PDSerializer");
 * @author PDGen
 */
public class PDSerializer implements PDInstance {

	public static final GUID typeId = new GUID("5f1e85348e0ede11980f9a097666e103"); 

	public static final GUID roleInstructionId = new GUID("611e85348e0ede11980f9a097666e103");

	static {
		DALClassRegister.addDataClass(typeId, PDSerializer.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDSerializer:" + name;
		else
			return "PDSerializer:" + id;
	}
	/**
	 * Creates an PDSerializer object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDSerializer(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDSerializer object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDSerializer(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDSerializer load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDSerializer)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "instruction".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDPrintInstruction getInstruction() throws PDStoreException {
	 	return (PDPrintInstruction)pdWorkingCopy.getInstance(this, roleInstructionId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "instruction".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDPrintInstruction> getInstructions() throws PDStoreException {
	 	Set<PDPrintInstruction> result = new HashSet<PDPrintInstruction>();
	 	GUID PDPrintInstructionTypeId = new GUID("621e85348e0ede11980f9a097666e103");
		pdWorkingCopy.getInstances(this, roleInstructionId, PDPrintInstruction.class, PDPrintInstructionTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "instruction".
	 * If the given instance is null, nothing happens.
	 * @param instruction the instance to connect
	 * @throws PDStoreException
	 */
	public void addInstruction(GUID instruction) throws PDStoreException {

			if (instruction != null) {
				
				pdWorkingCopy.addLink(this.id, roleInstructionId, instruction);
			}

	}

	/**
	 * Connects this instance to the given instance using role "instruction".
	 * If the given instance is null, nothing happens.
	 * @param instruction the instance to connect
	 * @throws PDStoreException
	 */
	public void addInstruction(PDPrintInstruction instruction) throws PDStoreException {
		if (instruction != null) {
			addInstruction(instruction.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "instruction".
	 * @throws PDStoreException
	 */
	public void removeInstruction() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleInstructionId, 
			pdWorkingCopy.getInstance(this, roleInstructionId));
	}

	/**
	 * Removes the link from this instance through role "instruction" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.instruction.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeInstruction(Object instruction) throws PDStoreException {
		if (instruction==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleInstructionId, instruction);
	}

   /**
	 * Connects this instance to the given instance using role "instruction".
	 * If there is already an instance connected to this instance through role "instruction", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param instruction the instance to connect
	 * @throws PDStoreException
	 */
	public void setInstruction(GUID instruction) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleInstructionId, instruction);	
	}
	/**
	 * Connects this instance to the given instance using role "instruction".
	 * If there is already an instance connected to this instance through role "instruction", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param instruction the instance to connect
	 * @throws PDStoreException
	 */
	public void setInstruction(PDPrintInstruction instruction) throws PDStoreException {
		setInstruction(instruction.getId());
	}

}
