package address.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Address" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("address.dal.PDAddress");
 * @author PDGen
 */
public class PDAddress implements PDInstance {

	public static final GUID typeId = new GUID("5c61caa043b111e08850842b2b9af4fd"); 

	public static final GUID roleStreetNameId = new GUID("5c61caa143b111e08850842b2b9af4fd");
	public static final GUID roleHouseNoId = new GUID("9e7190b243b111e08de5842b2b9af4fd");
	public static final GUID roleCustomerId = new GUID("9e7190b043b111e08de5842b2b9af4fc");

	static {
		DALClassRegister.addDataClass(typeId, PDAddress.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDAddress:" + name;
		else
			return "PDAddress:" + id;
	}
	/**
	 * Creates an PDAddress object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDAddress(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDAddress object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDAddress(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDAddress load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDAddress)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "streetName".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public String getStreetName() throws PDStoreException {
	 	return (String)pdWorkingCopy.getInstance(this, roleStreetNameId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "streetName".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<String> getStreetNames() throws PDStoreException {
	 	Set<String> result = new HashSet<String>();
	 	GUID StringTypeId = new GUID("4a8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleStreetNameId, String.class, StringTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "streetName".
	 * If the given instance is null, nothing happens.
	 * @param streetName the instance to connect
	 * @throws PDStoreException
	 */
	public void addStreetName(String streetName) throws PDStoreException {

			if (streetName != null) {
				
				pdWorkingCopy.addLink(this.id, roleStreetNameId, streetName);
			}

	}


	/**
	 * Removes the link from this instance through role "streetName".
	 * @throws PDStoreException
	 */
	public void removeStreetName() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleStreetNameId, 
			pdWorkingCopy.getInstance(this, roleStreetNameId));
	}

	/**
	 * Removes the link from this instance through role "streetName" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.streetName.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeStreetName(Object streetName) throws PDStoreException {
		if (streetName==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleStreetNameId, streetName);
	}

   /**
	 * Connects this instance to the given instance using role "streetName".
	 * If there is already an instance connected to this instance through role "streetName", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param streetName the instance to connect
	 * @throws PDStoreException
	 */
	public void setStreetName(String streetName) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleStreetNameId, streetName);	
	}
  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "houseNo".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public Long getHouseNo() throws PDStoreException {
	 	return (Long)pdWorkingCopy.getInstance(this, roleHouseNoId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "houseNo".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<Long> getHouseNos() throws PDStoreException {
	 	Set<Long> result = new HashSet<Long>();
	 	GUID LongTypeId = new GUID("4b8a986c4062db11afc0b95b08f50e2f");
		pdWorkingCopy.getInstances(this, roleHouseNoId, Long.class, LongTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "houseNo".
	 * If the given instance is null, nothing happens.
	 * @param houseNo the instance to connect
	 * @throws PDStoreException
	 */
	public void addHouseNo(Long houseNo) throws PDStoreException {

			if (houseNo != null) {
				
				pdWorkingCopy.addLink(this.id, roleHouseNoId, houseNo);
			}

	}


	/**
	 * Removes the link from this instance through role "houseNo".
	 * @throws PDStoreException
	 */
	public void removeHouseNo() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleHouseNoId, 
			pdWorkingCopy.getInstance(this, roleHouseNoId));
	}

	/**
	 * Removes the link from this instance through role "houseNo" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.houseNo.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeHouseNo(Object houseNo) throws PDStoreException {
		if (houseNo==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleHouseNoId, houseNo);
	}

   /**
	 * Connects this instance to the given instance using role "houseNo".
	 * If there is already an instance connected to this instance through role "houseNo", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param houseNo the instance to connect
	 * @throws PDStoreException
	 */
	public void setHouseNo(Long houseNo) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleHouseNoId, houseNo);	
	}
  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "customer".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDCustomer getCustomer() throws PDStoreException {
	 	return (PDCustomer)pdWorkingCopy.getInstance(this, roleCustomerId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "customer".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDCustomer> getCustomers() throws PDStoreException {
	 	Set<PDCustomer> result = new HashSet<PDCustomer>();
	 	GUID PDCustomerTypeId = new GUID("9e70a65043b111e08de5842b2b9af4fd");
		pdWorkingCopy.getInstances(this, roleCustomerId, PDCustomer.class, PDCustomerTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "customer".
	 * If the given instance is null, nothing happens.
	 * @param customer the instance to connect
	 * @throws PDStoreException
	 */
	public void addCustomer(GUID customer) throws PDStoreException {

			if (customer != null) {
				
				pdWorkingCopy.addLink(this.id, roleCustomerId, customer);
			}

	}

	/**
	 * Connects this instance to the given instance using role "customer".
	 * If the given instance is null, nothing happens.
	 * @param customer the instance to connect
	 * @throws PDStoreException
	 */
	public void addCustomer(PDCustomer customer) throws PDStoreException {
		if (customer != null) {
			addCustomer(customer.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "customer".
	 * @throws PDStoreException
	 */
	public void removeCustomer() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleCustomerId, 
			pdWorkingCopy.getInstance(this, roleCustomerId));
	}

	/**
	 * Removes the link from this instance through role "customer" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.customer.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeCustomer(Object customer) throws PDStoreException {
		if (customer==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleCustomerId, customer);
	}

   /**
	 * Connects this instance to the given instance using role "customer".
	 * If there is already an instance connected to this instance through role "customer", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param customer the instance to connect
	 * @throws PDStoreException
	 */
	public void setCustomer(GUID customer) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleCustomerId, customer);	
	}
	/**
	 * Connects this instance to the given instance using role "customer".
	 * If there is already an instance connected to this instance through role "customer", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param customer the instance to connect
	 * @throws PDStoreException
	 */
	public void setCustomer(PDCustomer customer) throws PDStoreException {
		setCustomer(customer.getId());
	}

}
