package address.dal;

import java.util.*;
import pdstore.*;
import pdstore.dal.*;

/**
 * Data access class to represent instances of type "Customer" in memory.
 * Note that this class needs to be registered with PDCache by calling:
 *    Class.forName("address.dal.PDCustomer");
 * @author PDGen
 */
public class PDCustomer implements PDInstance {

	public static final GUID typeId = new GUID("9e70a65043b111e08de5842b2b9af4fd"); 

	public static final GUID roleAddressId = new GUID("9e7190b043b111e08de5842b2b9af4fd");

	static {
		DALClassRegister.addDataClass(typeId, PDCustomer.class);
	}
	private PDWorkingCopy pdWorkingCopy;
	private GUID id;
	public String toString() {
		String name = getName();
		if(name!=null)
			return "PDCustomer:" + name;
		else
			return "PDCustomer:" + id;
	}
	/**
	 * Creates an PDCustomer object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 */
	public PDCustomer(PDWorkingCopy workingCopy) {
		this(workingCopy, new GUID());
	}
	
	/**
	 * Creates an PDCustomer object representing the given instance in the given cache.
	 * @param workingCopy the working copy the instance should be in
	 * @param id GUID of the instance
	 */
	public PDCustomer(PDWorkingCopy workingCopy, GUID id) {
		this.pdWorkingCopy = workingCopy;
		this.id = id;
		
		
	}
	/**
	 * Loads an instance object of this type into a cache.
	 * If the instance is already in the cache, the cached instance is returned.
	 * @param PDWorkingCopy pdWorkingCopy to load the instance into
	 * @param id GUID of the instance
	 * Do not directly call this method. Use the newInstance() method in PDCache which would call this method
	 */
	public static PDCustomer load(PDWorkingCopy pdWorkingCopy, GUID id) {
		PDInstance instance = pdWorkingCopy.load(typeId, id);
		return (PDCustomer)instance;
	}

	/**
	 * Gets the pdWorkingCopy this object is stored in.
	 */
	public PDWorkingCopy getPDWorkingCopy() {
		return pdWorkingCopy;
	}
	/**
	 * Gets the GUID of the instance represented by this object.
	 */
	public GUID getId() {
		return id;
	}
	/**
	 * Gets the GUID of the type of the instance represented by this object.
	 */
	public GUID getTypeId() {
		return typeId;
	}
	/**
	 * Gets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * @return name the instance name
	 * @throws PDStoreException
	 */
	public String getName() throws PDStoreException {
		return pdWorkingCopy.getName(id);
	}
	/**
	 * Sets the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance already has a name, the name will be overwritten.
	 * If the given name is null, an existing name will be removed.
	 * @return name the new instance name
	 * @throws PDStoreException
	 */
	public void setName(String name) throws PDStoreException {
		pdWorkingCopy.setName(id, name);
	}
	/**
	 * Removes the name of this instance.
	 * In PDStore every instance can be given a name.
	 * If the instance does not have a name, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeName() throws PDStoreException {
		pdWorkingCopy.removeName(id);
	}
	/**
	 * Gets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * @return icon the instance icon
	 * @throws PDStoreException
	 */
	public Blob getIcon() throws PDStoreException {
		return pdWorkingCopy.getIcon(id);
	}
	/**
	 * Sets the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance already has an icon, the icon will be overwritten.
	 * If the given icon is null, an existing icon will be removed.
	 * @return icon the new instance icon
	 * @throws PDStoreException
	 */
	public void setIcon(Blob icon) throws PDStoreException {
		pdWorkingCopy.setIcon(id, icon);
	}
	/**
	 * Removes the icon of this instance.
	 * In PDStore every instance can be given an icon.
	 * If the instance does not have an icon, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeIcon() throws PDStoreException {
		pdWorkingCopy.removeIcon(id);
	}

	
	  // Code generated by PDGetSetRemoveGen:


	/**
	 * Returns the instance connected to this instance through the role "address".
	 * @return the connected instance
	 * @throws PDStoreException
	 */
	 public PDAddress getAddress() throws PDStoreException {
	 	return (PDAddress)pdWorkingCopy.getInstance(this, roleAddressId);
	 }

	/**
	 * Returns the instance(s) connected to this instance through the role "address".
	 * @return the connected instance(s)
	 * @throws PDStoreException
	 */
	 public Collection<PDAddress> getAddresss() throws PDStoreException {
	 	Set<PDAddress> result = new HashSet<PDAddress>();
	 	GUID PDAddressTypeId = new GUID("5c61caa043b111e08850842b2b9af4fd");
		pdWorkingCopy.getInstances(this, roleAddressId, PDAddress.class, PDAddressTypeId, result);
	 	return result;
	 }
	 
   /**
	 * Connects this instance to the given instance using role "address".
	 * If the given instance is null, nothing happens.
	 * @param address the instance to connect
	 * @throws PDStoreException
	 */
	public void addAddress(GUID address) throws PDStoreException {

			if (address != null) {
				
				pdWorkingCopy.addLink(this.id, roleAddressId, address);
			}

	}

	/**
	 * Connects this instance to the given instance using role "address".
	 * If the given instance is null, nothing happens.
	 * @param address the instance to connect
	 * @throws PDStoreException
	 */
	public void addAddress(PDAddress address) throws PDStoreException {
		if (address != null) {
			addAddress(address.getId());
		}		
	}

	/**
	 * Removes the link from this instance through role "address".
	 * @throws PDStoreException
	 */
	public void removeAddress() throws PDStoreException {
		pdWorkingCopy.removeLink(this.id, roleAddressId, 
			pdWorkingCopy.getInstance(this, roleAddressId));
	}

	/**
	 * Removes the link from this instance through role "address" to the given instance, if the link exists.
	 * If there is no such link, nothing happens.address.getId()
	 * If the given instance is null, nothing happens.
	 * @throws PDStoreException
	 */
	public void removeAddress(Object address) throws PDStoreException {
		if (address==null)
			return;
		pdWorkingCopy.removeLink(this.id, roleAddressId, address);
	}

   /**
	 * Connects this instance to the given instance using role "address".
	 * If there is already an instance connected to this instance through role "address", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param address the instance to connect
	 * @throws PDStoreException
	 */
	public void setAddress(GUID address) throws PDStoreException {
		pdWorkingCopy.setLink(this.id,  roleAddressId, address);	
	}
	/**
	 * Connects this instance to the given instance using role "address".
	 * If there is already an instance connected to this instance through role "address", the link will be overwritten.
	 * If the given instance is null, an existing link is removed."
	 * @param address the instance to connect
	 * @throws PDStoreException
	 */
	public void setAddress(PDAddress address) throws PDStoreException {
		setAddress(address.getId());
	}

}
