package address;

import pdstore.*;
import pdstore.dal.*;

public class CreateAddressModel {
	public static void main(String[] args) {
		PDStore store = new PDStore("MyDatabaseFile");
		GUID transaction = store.begin();

		// create a new model, with a new GUID (generated by GUIDGen)
		GUID model = new GUID("5c60e04043b111e08850842b2b9af4fd");
		store.createModel(transaction, model, "AddressModel");

		// create the new complex type Customer
		GUID customerType = new GUID("9e70a65043b111e08de5842b2b9af4fd");
		store.createType(transaction, model, customerType, "Customer");
		
		// create the new complex type Address
		GUID addressType = new GUID("5c61caa043b111e08850842b2b9af4fd");
		store.createType(transaction, model, addressType, "Address");
		
		// create relation from Customer to Address
		GUID addressRole = new GUID("9e7190b043b111e08de5842b2b9af4fd");
		store.createRelation(transaction, customerType, "customer", "address",
				addressRole, addressType);

		// create relation from Address to street name
		GUID streetNameRole = new GUID("5c61caa143b111e08850842b2b9af4fd");
		store.createRelation(transaction, addressType, "address", "streetName",
				streetNameRole, PDStore.STRING_TYPEID);
		
		// create relation from Address to house no
		GUID houseNoRole = new GUID("9e7190b243b111e08de5842b2b9af4fd");
		store.createRelation(transaction, addressType, "address", "houseNo",
				houseNoRole, PDStore.INTEGER_TYPEID);

		store.commit(transaction);

		// generate DAL into package "address.dal" in folder "examples"
		PDWorkingCopy copy = new PDSimpleWorkingCopy(store);
		PDGen.generateModel("AddressModel", "examples", copy, "address.dal");
	}
}
